### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by Numsgil** [TheCreatorJames/DotNetCompressor#1]
Can you add a license file to this project?  (Ideally something permissive like [MIT](https://en.wikipedia.org/wiki/MIT_License) and not the GPL would be nice :))

**Comment by TotalTechGeek** [comment]
Sure!

**Comment by TotalTechGeek** [comment]
Well, after adding the license I realized that SevenZipSharp is licensed under LGPL, this shouldn't  affect the MIT license I just placed on the application, but I am re-opening this issue to remind myself to research the issue further and include all relevant attributions.

**Comment by Numsgil** [comment]
IANAL, but if you're embedding SevenZipSharp in to the user's binary, then their binary inherits the LGPL requirements.  Which is rather restrictive.

If I'm reading your code correctly, it only uses SevenZipSharp if the user requests LZMA compression, right?  Does it only embed SevenZipSharp in to the user's binary if they're using LZMA?  If so, then not using LZMA compression means the LGPL requirements won't leak in to the user's binary.  Since you're not embedding SevenZipSharp in to your own binary, your own code should likewise be "protected" from LGPL and the MIT license holds as the most restrictive.

If you were to distribute a DotNetCompressor binary in the future, you'd need to be sure not to embed SevenZipSharp in to your own binary, unless you're willing to release the source code as MIT license and the binary as LGPL license.  Which you could certainly do, but it's maybe a bit confusing.

You might want to make a note in the readme that if the user uses LZMA compression they'll end up inheriting the LGPL license in to their binary.  You could think about adding an option to leave SevenZipSharp.dll separate from the client binary, so that the license doesn't get inherited, but that does mean clients end up with 2 binaries to manage.

Again, IANAL, so take my recommendations/interpretations with a grain of salt.

**Comment by TotalTechGeek** [comment]
Sorry for not closing this issue sooner. 

The new update removes SevenZipSharp, and uses a different (permissive) compression library. 

The MIT License should now be in an unambiguous place.
